export const paramsArray = [
    {
      paramName: "names",
      xCoordinate: null,
      yCoordinate: null,
      color: "ffaa00",
      font: "New Roman",
      fontBold: "public/fonts/Alegreya_Sans/AlegreyaSans-Bold.ttf",
      fontMedium: "public/fonts/Alegreya_Sans/AlegreyaSans-Medium.ttf",
      fontColor: "ffaa00",
      fontSize: 30,
      fontStyle: "normal",
      textAlign: "left",
      width: null,
      breadth: 210,
    },
    {
      paramName: "memberclass",
      xCoordinate: null,
      yCoordinate: null,
      color: "ffaa00",
      font: "New Roman",
      fontBold: "public/fonts/Alegreya_Sans/AlegreyaSans-Bold.ttf",
      fontMedium: "public/fonts/Alegreya_Sans/AlegreyaSans-Medium.ttf",
      fontColor: "ffaa00",
      fontSize: 30,
      fontStyle: "normal",
      textAlign: "left",
      width: null,
      breadth: 210,
    },
    {
      paramName: "discipline",
      xCoordinate: null,
      yCoordinate: null,
      color: "ffaa00",
      font: "New Roman",
      fontBold: "public/fonts/Alegreya_Sans/AlegreyaSans-Bold.ttf",
      fontMedium: "public/fonts/Alegreya_Sans/AlegreyaSans-Medium.ttf",
      fontColor: "ffaa00",
      fontSize: 30,
      fontStyle: "normal",
      textAlign: "left",
      width: null,
      breadth: 210,
    },
    {
      paramName: "photo",
      xCoordinate: null,
      yCoordinate: null,
      width: null,
      breadth: 510,
    },
    {
      paramName: "QR",
      xCoordinate: null,
      yCoordinate: null,
      width: null,
      breadth: 510,
    },
  ]
